### ISSUE TITLE
Support endpoint-series

### ISSUE THREAD

**Issue by runar-rkmedia** [runar-rkmedia/audio-mirror#2]
For some advanced api's,  support is needed for running series of requests towards an apis. Consider for instance NRKs apis for retrieving a URL to an episode.

For a given seriesID, like for instance `historiske_kjendiser`, these requests must be resolved:

Get list of episodes: `GET https://psapi.nrk.no/radio/catalog/podcast/historiske_kjendiser`

For each episode, find the `episodeId`, like for instance `l_30b10fdd-54d8-46d0-b10f-dd54d886d01e` that can be used with the url `https://psapi.nrk.no/playback/manifest/podcast/historiske_kjendiser/l_30b10fdd-54d8-46d0-b10f-dd54d886d01e` This has the object of interest like: 

```yaml
URL:	"https://podkast.nrk.no/fil/historiske_kjendiser/899c79cb-5cb4-4fea-b963-bf789e8192c9_0_ID192MP3.mp3"
format:	"MP3"
mimeType:	"audio/mp3"
encrypted:	false
encryptionScheme:	"none"
````

(ignoring the fact that NRK seems to be encrypting some episodes for now)

For this case, we could solve it in two ways:

1. Add a new endpoint-type for retrieving more information about a given episode.
2. Add support for series of episodes.

I do think we need support for both of these.

Do note that there currently is support for multiple requests for the same type, but they cannot link to each others information, or mark one as dependant on the other.

Consider adding an optional local identifier for each endpoint, and an optional array with dependsOn, where one can mark dependencies.

```yaml
episodeEndpoints:
- URL: `/manifest/podcast/historiske_kjendiser/l_30b10fdd-54d8-46d0-b10f-dd54d886d01e`
- URL: `/manifest/podcast/historiske_kjendiser/l_30b10fdd-54d8-46d0-b10f-dd54d886d01e`
https://psapi.nrk.no/playback/manifest/podcast/historiske_kjendiser/l_30b10fdd-54d8-46d0-b10f-dd54d886d01e


```
